SoftValley/Models/ErrorViewModel.cs
namespace SoftValley.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SoftValley/Controllers/AspController.cs
using Microsoft.AspNetCore.Mvc;

namespace SoftValley.Controllers
{
    public class AspController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SoftValley/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SoftValley.Models;
using System.Diagnostics;

namespace SoftValley.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

     

     
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SoftValley/Controllers/UnityController.cs
using Microsoft.AspNetCore.Mvc;

namespace SoftValley.Controllers
{
    public class UnityController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SoftValley/Views/Asp/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    이곳은 ASP를 게시할 곳입니다
</body>
</html>

SoftValley/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "안녕하세요^^";
}



<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>


    <div class="text-center border">
    
        <h1 class="display-4">안녕하세요!</h1>
        <hr />
        <p>
            이곳은 <h6>최동현</h6>의 취업을위해 공부하였던 내용을 정리해놓은 곳입니다.
            <br />
            현재페이지는 ASP.NET Core MVC패턴을 사용하여 구축하였습니다.
            <br />
            서버는 Microsoft Azure를 사용 하였습니다.
        </p>
    
    </div>
    <hr />

        <div class="border shadow-lg" >
    <table class="border">

        <tr>
        
            <td>
                <a asp-controller="Unity" asp-action="Index"> <img src="/c.png" height="160" width="178" class="border-light shadow-lg" /> </a>
                <a asp-controller="Asp" asp-action="Index"> <img src="/net.jpg" height="160" width="178" class="border-light shadow-lg" /> </a>
                <a asp-controller="Unity" asp-action="Index"> <img src="/sq.png" height="160" width="178" class="border-light shadow-lg" /> </a>
                <a asp-controller="Unity" asp-action="Index"> <img src="/unity.jpg" height="160" width="178" class="border-light shadow-lg" /> </a>
                <a href="https://github.com/Choi-Dong-Hyeon"> <img src="/git.png" height="160" width="178" class="border-light shadow-lg" /> </a>
                

                <a asp-controller="Unity" asp-action="Index"> <img src="/htmlcs.png" height="160" width="178" class="border-light shadow-lg" /> </a>
                


            </td>
        </tr>
    </table>
        </div>


   

    <hr />
</body>
</html>

    <footer>
        푸터
    </footer>

SoftValley/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SoftValley.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SoftValley</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">홈</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="">유니티</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">CRUD게시판</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-area="" asp-controller="Home" asp-action="Privacy"  >개인정보처리방침</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SoftValley - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SoftValley/Views/Unity/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>

    이곳은 유니티 작업을 게시할것입니다.
    <a asp-controller="Unity" asp-action="Index"> <img src="/git.png" height="170" width="185" class="border-light shadow-lg" /> </a>

   
       

            <a href="/JumpGame/index.html">Click Jump Play <img src="/JumpGame/icon.png" alt="Alternate Text" width="100" /> </a>
       
</body>
</html>